[package]
name = "macroman-encode"
description = "No-nonsense no_std conversion from Unicode to MacRoman"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Solra Bizna <solra@bizna.name>"]

[dependencies]
